version: '3'

services:
  mycroft:
    image: mycroft
    environment: 
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    volumes:
      - data:/root/.mycroft
      - skills:/opt/mycroft/skills
      - ./crm-skill:/opt/mycroft/skills/crm-skill
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie
    devices: 
      - /dev/snd
    ports:
      - 8181:8181
    
volumes:
  data:
  skills:
