@startuml add relationship
skinparam SequenceMessageAlignment center
autonumber

title Add relationship

actor User as u
participant Mycroft as m

u -> m: "new relationship" utt

== State 0 ==
alt utt does not contain contact names
    m --> u: who is the first contact?
    u -> m: utt
    m -> m: action hotword handling\n(stop, repeat)

    m -> m: check db

    alt contact not found
        m --> u: add them?
        u -> m: utt (y/n)
        alt affirmation
            m -> m: call new contact task
            alt new contact task aborted/failed
                m --x u: bye
            end
            m -> m: get the new contact
            m -> m: go to next state
        end
    else multiple contacts
        loop for each contact
            m --> u: do you mean $nickname?
            u -> m: utt (y/n)
            alt affirmation
                m --> u: inform
                m -> m: next state
            end
        end
    end
    m --x u: bye
end

== State 1 ==
alt utt does not contain {relationship}
    m --> u: what is the relationship?
    u -> m: utt
    m -> m: action hotword handling\n(stop, repeat)
end

== State 2 ==
alt utt does not contain contact names
    m --> u: who is the second contact?
    u -> m: utt
    m -> m: action hotword handling\n(stop, repeat)

    m -> m: check db

    alt contact not found
        m --> u: add them?
        u -> m: utt (y/n)
        alt affirmation
            m -> m: call new contact task
            alt new contact task aborted/failed
                m --x u: bye
            end
            m -> m: get the new contact
            m -> m: go to next state
        end
    else multiple contacts
        loop for each contact
            m --> u: do you mean $nickname?
            u -> m: utt (y/n)
            alt affirmation
                m --> u: inform
                m -> m: next state
            end
        end
    end
    m --x u: bye
end

== State 3 ==
alt contact1 == contact2
    m --> u: same contact
    m -> m: go to state 2
end

alt already exists a family relationship\nbetween the two contacts
    m --> u: {old_relationship} already exists\nreplace it with {relationship}?
    u -> m: utt (y/n)
    alt negation
        m --x u: bye
    else
        m -> m: delete {old_relationship}
    end

end

m -> m: add the specified relationship\nbetween the given contacts
m --> u: bye

@enduml