@startuml new contact
skinparam SequenceMessageAlignment center
autonumber

title New contact

actor User as u
participant Mycroft as m

u -> m: "new contact" utt
== State 0 ==
alt utt does not contain {surname}
    m --> u: surname?
    u -> m: utt
    m -> m: action hotword handling\n(stop, repeat)
end

== State 1 ==
alt utt does not contain {name}
    m --> u: name?
    u -> m: utt
    m -> m: action hotword handling\n(stop, repeat)
end

== State DB ==

m -> m: db check
alt contact exists
    m --> u: contact exists,\nsure to proceed?
    u -> m: utt (y/n)
    alt affirmation
        m -> m: nickname mandatory = yes
        m -> m: go to next state
    end
    m --x u: bye
end

== State 2 ==
m --> u: nickname?
u -> m: utt
m -> m: action hotword handling\n(stop, repeat, back,\nskip (if nickname not mandatory))
alt nickname not unique
    m --> u: inform
    m -> m: restart current state
end

== State 3 ==
m -> m: save contact

== State 4 ==
m --> u: more details?
u -> m: utt (y/n)
alt negation
    m -x u: end
end

== State 5 ==
m --> u: gender?
u -> m: utt
m -> m: action hotword handling\n(stop, repeat, back, skip)
m -> m: save

== State 6 ==
m --> u: birth date?
u -> m: utt
m -> m: action hotword handling\n(stop, repeat, back, skip)
m -> m: save

== State 7 ==
m --> u: bye

@enduml