@startuml new activity
skinparam SequenceMessageAlignment center
autonumber

title New activity

actor User as u
participant Mycroft as m

u -> m: "new activity" utt

== State 0 ==
alt utt does not containt {person}
    m --> u: with whom?
    u -> m: utt
    m -> m: action hotword handling\n(stop, repeat)
end

m -> m: check db

alt contact not found
    m --> u: add them?
    u -> m: utt (y/n)
    alt affirmation
        m -> m: call new contact task
        alt new contact task aborted/failed
            m --x u: bye
        end
        m -> m: get the new contact
        m -> m: go to next state
    end
else multiple contacts
    loop for each contact
        m --> u: do you mean $nickname?
        u -> m: utt (y/n)
        alt affirmation
            m --> u: inform
            m -> m: next state
        end
    end
end
m --x u: bye

== State 1 ==
alt initial utt does not contain {activity}
    m --> u: activity?
    u -> m: utt
    m -> m: action hotword handling\n(stop, back, repeat)
end

== State 2 ==
alt initial utt does not contain {datetime}
    m --> u: when?
    u -> m: utt
    m -> m: action hotword handling\n(stop, back, repeat)
end

m -> m: save activity with given data

m --> u: bye

@enduml